// Generated by gencpp from file low_level_controllers/tip.msg
// DO NOT EDIT!


#ifndef LOW_LEVEL_CONTROLLERS_MESSAGE_TIP_H
#define LOW_LEVEL_CONTROLLERS_MESSAGE_TIP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace low_level_controllers
{
template <class ContainerAllocator>
struct tip_
{
  typedef tip_<ContainerAllocator> Type;

  tip_()
    : x_l(0)
    , y_l(0)
    , z_l(0)
    , x_r(0)
    , y_r(0)
    , z_r(0)  {
    }
  tip_(const ContainerAllocator& _alloc)
    : x_l(0)
    , y_l(0)
    , z_l(0)
    , x_r(0)
    , y_r(0)
    , z_r(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_l_type;
  _x_l_type x_l;

   typedef int64_t _y_l_type;
  _y_l_type y_l;

   typedef int64_t _z_l_type;
  _z_l_type z_l;

   typedef int64_t _x_r_type;
  _x_r_type x_r;

   typedef int64_t _y_r_type;
  _y_r_type y_r;

   typedef int64_t _z_r_type;
  _z_r_type z_r;





  typedef boost::shared_ptr< ::low_level_controllers::tip_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::low_level_controllers::tip_<ContainerAllocator> const> ConstPtr;

}; // struct tip_

typedef ::low_level_controllers::tip_<std::allocator<void> > tip;

typedef boost::shared_ptr< ::low_level_controllers::tip > tipPtr;
typedef boost::shared_ptr< ::low_level_controllers::tip const> tipConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::low_level_controllers::tip_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::low_level_controllers::tip_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace low_level_controllers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'low_level_controllers': ['/home/thilina/development/robot_ws/Robot_ws/src/low_level_controllers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::low_level_controllers::tip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::low_level_controllers::tip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level_controllers::tip_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::low_level_controllers::tip_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level_controllers::tip_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::low_level_controllers::tip_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::low_level_controllers::tip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b9355347ab78a212e75bdc6efe75148";
  }

  static const char* value(const ::low_level_controllers::tip_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b9355347ab78a21ULL;
  static const uint64_t static_value2 = 0x2e75bdc6efe75148ULL;
};

template<class ContainerAllocator>
struct DataType< ::low_level_controllers::tip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "low_level_controllers/tip";
  }

  static const char* value(const ::low_level_controllers::tip_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::low_level_controllers::tip_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x_l\n\
int64 y_l\n\
int64 z_l\n\
int64 x_r\n\
int64 y_r\n\
int64 z_r\n\
\n\
";
  }

  static const char* value(const ::low_level_controllers::tip_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::low_level_controllers::tip_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_l);
      stream.next(m.y_l);
      stream.next(m.z_l);
      stream.next(m.x_r);
      stream.next(m.y_r);
      stream.next(m.z_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tip_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::low_level_controllers::tip_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::low_level_controllers::tip_<ContainerAllocator>& v)
  {
    s << indent << "x_l: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x_l);
    s << indent << "y_l: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y_l);
    s << indent << "z_l: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z_l);
    s << indent << "x_r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x_r);
    s << indent << "y_r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y_r);
    s << indent << "z_r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOW_LEVEL_CONTROLLERS_MESSAGE_TIP_H
