# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from low_level_controllers/tip.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class tip(genpy.Message):
  _md5sum = "3b9355347ab78a212e75bdc6efe75148"
  _type = "low_level_controllers/tip"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 x_l
int64 y_l
int64 z_l
int64 x_r
int64 y_r
int64 z_r

"""
  __slots__ = ['x_l','y_l','z_l','x_r','y_r','z_r']
  _slot_types = ['int64','int64','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x_l,y_l,z_l,x_r,y_r,z_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(tip, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x_l is None:
        self.x_l = 0
      if self.y_l is None:
        self.y_l = 0
      if self.z_l is None:
        self.z_l = 0
      if self.x_r is None:
        self.x_r = 0
      if self.y_r is None:
        self.y_r = 0
      if self.z_r is None:
        self.z_r = 0
    else:
      self.x_l = 0
      self.y_l = 0
      self.z_l = 0
      self.x_r = 0
      self.y_r = 0
      self.z_r = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.x_l, _x.y_l, _x.z_l, _x.x_r, _x.y_r, _x.z_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_l, _x.y_l, _x.z_l, _x.x_r, _x.y_r, _x.z_r,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6q().pack(_x.x_l, _x.y_l, _x.z_l, _x.x_r, _x.y_r, _x.z_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.x_l, _x.y_l, _x.z_l, _x.x_r, _x.y_r, _x.z_r,) = _get_struct_6q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6q = None
def _get_struct_6q():
    global _struct_6q
    if _struct_6q is None:
        _struct_6q = struct.Struct("<6q")
    return _struct_6q
