# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from more_custom_msgs/Sfl_Motion_Target.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Sfl_Motion_Target(genpy.Message):
  _md5sum = "6c5240ea2332e8eacd5795f6b9de6e18"
  _type = "more_custom_msgs/Sfl_Motion_Target"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint16         id
uint16         center
uint8          width
uint8          height
uint8          distance
"""
  __slots__ = ['id','center','width','height','distance']
  _slot_types = ['uint16','uint16','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,center,width,height,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Sfl_Motion_Target, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.center is None:
        self.center = 0
      if self.width is None:
        self.width = 0
      if self.height is None:
        self.height = 0
      if self.distance is None:
        self.distance = 0
    else:
      self.id = 0
      self.center = 0
      self.width = 0
      self.height = 0
      self.distance = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2H3B().pack(_x.id, _x.center, _x.width, _x.height, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.id, _x.center, _x.width, _x.height, _x.distance,) = _get_struct_2H3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2H3B().pack(_x.id, _x.center, _x.width, _x.height, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.id, _x.center, _x.width, _x.height, _x.distance,) = _get_struct_2H3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H3B = None
def _get_struct_2H3B():
    global _struct_2H3B
    if _struct_2H3B is None:
        _struct_2H3B = struct.Struct("<2H3B")
    return _struct_2H3B
