(cl:in-package more_custom_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SERIALNUMBER-VAL
          SERIALNUMBER
          ERROR-VAL
          ERROR
          VOLTAGE0-VAL
          VOLTAGE0
          CURRENT0-VAL
          CURRENT0
          VOLTAGE1-VAL
          VOLTAGE1
          CURRENT1-VAL
          CURRENT1
          VOLTAGE2-VAL
          VOLTAGE2
          CURRENT2-VAL
          CURRENT2
          HEADING-VAL
          HEADING
          TEMPERATURE0-VAL
          TEMPERATURE0
          TEMPERATURE1-VAL
          TEMPERATURE1
          TEMPERATURE2-VAL
          TEMPERATURE2
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
))