(cl:in-package more_custom_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_UTC_USEC-VAL
          TIME_UTC_USEC
          LAT-VAL
          LAT
          LON-VAL
          LON
          ALT-VAL
          ALT
          ALT_ELLIPSOID-VAL
          ALT_ELLIPSOID
          S_VARIANCE_M_S-VAL
          S_VARIANCE_M_S
          C_VARIANCE_RAD-VAL
          C_VARIANCE_RAD
          EPH-VAL
          EPH
          EPV-VAL
          EPV
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          NOISE_PER_MS-VAL
          NOISE_PER_MS
          JAMMING_INDICATOR-VAL
          JAMMING_INDICATOR
          VEL_M_S-VAL
          VEL_M_S
          VEL_N_M_S-VAL
          VEL_N_M_S
          VEL_E_M_S-VAL
          VEL_E_M_S
          VEL_D_M_S-VAL
          VEL_D_M_S
          COG_RAD-VAL
          COG_RAD
          TIMESTAMP_TIME_RELATIVE-VAL
          TIMESTAMP_TIME_RELATIVE
          FIX_TYPE-VAL
          FIX_TYPE
          VEL_NED_VALID-VAL
          VEL_NED_VALID
          SATELLITES_USED-VAL
          SATELLITES_USED
))