// Generated by gencpp from file more_custom_msgs/Macro_Measurement.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_MACRO_MEASUREMENT_H
#define MORE_CUSTOM_MSGS_MESSAGE_MACRO_MEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace more_custom_msgs
{
template <class ContainerAllocator>
struct Macro_Measurement_
{
  typedef Macro_Measurement_<ContainerAllocator> Type;

  Macro_Measurement_()
    : a_deg(0.0)
    , r_m(0.0)  {
    }
  Macro_Measurement_(const ContainerAllocator& _alloc)
    : a_deg(0.0)
    , r_m(0.0)  {
  (void)_alloc;
    }



   typedef double _a_deg_type;
  _a_deg_type a_deg;

   typedef double _r_m_type;
  _r_m_type r_m;





  typedef boost::shared_ptr< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> const> ConstPtr;

}; // struct Macro_Measurement_

typedef ::more_custom_msgs::Macro_Measurement_<std::allocator<void> > Macro_Measurement;

typedef boost::shared_ptr< ::more_custom_msgs::Macro_Measurement > Macro_MeasurementPtr;
typedef boost::shared_ptr< ::more_custom_msgs::Macro_Measurement const> Macro_MeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b62fd7c9922c1d5039097daa12597aa";
  }

  static const char* value(const ::more_custom_msgs::Macro_Measurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b62fd7c9922c1d5ULL;
  static const uint64_t static_value2 = 0x039097daa12597aaULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/Macro_Measurement";
  }

  static const char* value(const ::more_custom_msgs::Macro_Measurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64         a_deg\n\
float64         r_m\n\
";
  }

  static const char* value(const ::more_custom_msgs::Macro_Measurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a_deg);
      stream.next(m.r_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Macro_Measurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::Macro_Measurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::Macro_Measurement_<ContainerAllocator>& v)
  {
    s << indent << "a_deg: ";
    Printer<double>::stream(s, indent + "  ", v.a_deg);
    s << indent << "r_m: ";
    Printer<double>::stream(s, indent + "  ", v.r_m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_MACRO_MEASUREMENT_H
