// Generated by gencpp from file more_custom_msgs/Process_TrackedTarget.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_H
#define MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace more_custom_msgs
{
template <class ContainerAllocator>
struct Process_TrackedTarget_
{
  typedef Process_TrackedTarget_<ContainerAllocator> Type;

  Process_TrackedTarget_()
    : header()
    , id(0)
    , x(0)
    , y(0)
    , heading(0)
    , speed(0.0)
    , cadence(0.0)
    , amplitude(0)
    , type(0)  {
    }
  Process_TrackedTarget_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , x(0)
    , y(0)
    , heading(0)
    , speed(0.0)
    , cadence(0.0)
    , amplitude(0)
    , type(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef uint16_t _heading_type;
  _heading_type heading;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _cadence_type;
  _cadence_type cadence;

   typedef uint16_t _amplitude_type;
  _amplitude_type amplitude;

   typedef uint8_t _type_type;
  _type_type type;





  typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> const> ConstPtr;

}; // struct Process_TrackedTarget_

typedef ::more_custom_msgs::Process_TrackedTarget_<std::allocator<void> > Process_TrackedTarget;

typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget > Process_TrackedTargetPtr;
typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget const> Process_TrackedTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc7ee22334e4fd9f26502f957a69a602";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc7ee22334e4fd9fULL;
  static const uint64_t static_value2 = 0x26502f957a69a602ULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/Process_TrackedTarget";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
 uint8 id\n\
 int32 x\n\
 int32 y\n\
 uint16 heading\n\
 float32 speed\n\
 float32 cadence\n\
 uint16 amplitude\n\
 uint8 type\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.heading);
      stream.next(m.speed);
      stream.next(m.cadence);
      stream.next(m.amplitude);
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Process_TrackedTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::Process_TrackedTarget_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "heading: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.heading);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "cadence: ";
    Printer<float>::stream(s, indent + "  ", v.cadence);
    s << indent << "amplitude: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.amplitude);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_H
