// Generated by gencpp from file more_custom_msgs/Process_TrackedTarget_Timeout.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_TIMEOUT_H
#define MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_TIMEOUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace more_custom_msgs
{
template <class ContainerAllocator>
struct Process_TrackedTarget_Timeout_
{
  typedef Process_TrackedTarget_Timeout_<ContainerAllocator> Type;

  Process_TrackedTarget_Timeout_()
    : header()
    , id(0)  {
    }
  Process_TrackedTarget_Timeout_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> const> ConstPtr;

}; // struct Process_TrackedTarget_Timeout_

typedef ::more_custom_msgs::Process_TrackedTarget_Timeout_<std::allocator<void> > Process_TrackedTarget_Timeout;

typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_Timeout > Process_TrackedTarget_TimeoutPtr;
typedef boost::shared_ptr< ::more_custom_msgs::Process_TrackedTarget_Timeout const> Process_TrackedTarget_TimeoutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5007c440e3148b7b250978b7733261cd";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5007c440e3148b7bULL;
  static const uint64_t static_value2 = 0x250978b7733261cdULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/Process_TrackedTarget_Timeout";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
 uint8     id\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Process_TrackedTarget_Timeout_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::Process_TrackedTarget_Timeout_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_PROCESS_TRACKEDTARGET_TIMEOUT_H
