// Generated by gencpp from file more_custom_msgs/Sfl_Motion_Targets.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_SFL_MOTION_TARGETS_H
#define MORE_CUSTOM_MSGS_MESSAGE_SFL_MOTION_TARGETS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <more_custom_msgs/Sfl_Motion_Target.h>

namespace more_custom_msgs
{
template <class ContainerAllocator>
struct Sfl_Motion_Targets_
{
  typedef Sfl_Motion_Targets_<ContainerAllocator> Type;

  Sfl_Motion_Targets_()
    : header()
    , serialnumber(0)
    , timestamp(0)
    , targets()  {
    }
  Sfl_Motion_Targets_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , serialnumber(0)
    , timestamp(0)
    , targets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _serialnumber_type;
  _serialnumber_type serialnumber;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef std::vector< ::more_custom_msgs::Sfl_Motion_Target_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::more_custom_msgs::Sfl_Motion_Target_<ContainerAllocator> >::other >  _targets_type;
  _targets_type targets;





  typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> const> ConstPtr;

}; // struct Sfl_Motion_Targets_

typedef ::more_custom_msgs::Sfl_Motion_Targets_<std::allocator<void> > Sfl_Motion_Targets;

typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Motion_Targets > Sfl_Motion_TargetsPtr;
typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Motion_Targets const> Sfl_Motion_TargetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f1c0607ec71b5df057827f572a8429b";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f1c0607ec71b5dfULL;
  static const uint64_t static_value2 = 0x057827f572a8429bULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/Sfl_Motion_Targets";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
uint32         serialnumber\n\
uint32         timestamp\n\
Sfl_Motion_Target[]   targets\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: more_custom_msgs/Sfl_Motion_Target\n\
uint16         id\n\
uint16         center\n\
uint8          width\n\
uint8          height\n\
uint8          distance\n\
";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.serialnumber);
      stream.next(m.timestamp);
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sfl_Motion_Targets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::Sfl_Motion_Targets_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "serialnumber: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.serialnumber);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "targets[]" << std::endl;
    for (size_t i = 0; i < v.targets.size(); ++i)
    {
      s << indent << "  targets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::more_custom_msgs::Sfl_Motion_Target_<ContainerAllocator> >::stream(s, indent + "    ", v.targets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_SFL_MOTION_TARGETS_H
