// Generated by gencpp from file more_custom_msgs/Sfl_Single_ValueStr.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_SFL_SINGLE_VALUESTR_H
#define MORE_CUSTOM_MSGS_MESSAGE_SFL_SINGLE_VALUESTR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace more_custom_msgs
{
template <class ContainerAllocator>
struct Sfl_Single_ValueStr_
{
  typedef Sfl_Single_ValueStr_<ContainerAllocator> Type;

  Sfl_Single_ValueStr_()
    : idx(0)
    , node_id()
    , value_str()  {
    }
  Sfl_Single_ValueStr_(const ContainerAllocator& _alloc)
    : idx(0)
    , node_id(_alloc)
    , value_str(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _idx_type;
  _idx_type idx;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_id_type;
  _node_id_type node_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _value_str_type;
  _value_str_type value_str;





  typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> const> ConstPtr;

}; // struct Sfl_Single_ValueStr_

typedef ::more_custom_msgs::Sfl_Single_ValueStr_<std::allocator<void> > Sfl_Single_ValueStr;

typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Single_ValueStr > Sfl_Single_ValueStrPtr;
typedef boost::shared_ptr< ::more_custom_msgs::Sfl_Single_ValueStr const> Sfl_Single_ValueStrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64a9c0509bedda8067728b2b3a4f3a8a";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64a9c0509bedda80ULL;
  static const uint64_t static_value2 = 0x67728b2b3a4f3a8aULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/Sfl_Single_ValueStr";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64          idx\n\
string         node_id\n\
string         value_str\n\
";
  }

  static const char* value(const ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idx);
      stream.next(m.node_id);
      stream.next(m.value_str);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sfl_Single_ValueStr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::Sfl_Single_ValueStr_<ContainerAllocator>& v)
  {
    s << indent << "idx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idx);
    s << indent << "node_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_id);
    s << indent << "value_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.value_str);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_SFL_SINGLE_VALUESTR_H
