// Generated by gencpp from file more_custom_msgs/SurveyInStatus.msg
// DO NOT EDIT!


#ifndef MORE_CUSTOM_MSGS_MESSAGE_SURVEYINSTATUS_H
#define MORE_CUSTOM_MSGS_MESSAGE_SURVEYINSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace more_custom_msgs
{
template <class ContainerAllocator>
struct SurveyInStatus_
{
  typedef SurveyInStatus_<ContainerAllocator> Type;

  SurveyInStatus_()
    : header()
    , mean_accuracy(0)
    , duration(0)
    , active(false)
    , valid(false)  {
    }
  SurveyInStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mean_accuracy(0)
    , duration(0)
    , active(false)
    , valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _mean_accuracy_type;
  _mean_accuracy_type mean_accuracy;

   typedef uint32_t _duration_type;
  _duration_type duration;

   typedef uint8_t _active_type;
  _active_type active;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SurveyInStatus_

typedef ::more_custom_msgs::SurveyInStatus_<std::allocator<void> > SurveyInStatus;

typedef boost::shared_ptr< ::more_custom_msgs::SurveyInStatus > SurveyInStatusPtr;
typedef boost::shared_ptr< ::more_custom_msgs::SurveyInStatus const> SurveyInStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace more_custom_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'more_custom_msgs': ['/home/thilina/development/robot_ws/Robot_ws/src/more_custom_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25fe686a6ed61b5f5c236127f6f3276c";
  }

  static const char* value(const ::more_custom_msgs::SurveyInStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25fe686a6ed61b5fULL;
  static const uint64_t static_value2 = 0x5c236127f6f3276cULL;
};

template<class ContainerAllocator>
struct DataType< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "more_custom_msgs/SurveyInStatus";
  }

  static const char* value(const ::more_custom_msgs::SurveyInStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint32 mean_accuracy\n\
uint32 duration\n\
bool active\n\
bool valid\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::more_custom_msgs::SurveyInStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mean_accuracy);
      stream.next(m.duration);
      stream.next(m.active);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SurveyInStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::more_custom_msgs::SurveyInStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::more_custom_msgs::SurveyInStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mean_accuracy: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mean_accuracy);
    s << indent << "duration: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.duration);
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORE_CUSTOM_MSGS_MESSAGE_SURVEYINSTATUS_H
