// Generated by gencpp from file custom_messages_module/myMessage.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MODULE_MESSAGE_MYMESSAGE_H
#define CUSTOM_MESSAGES_MODULE_MESSAGE_MYMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_messages_module
{
template <class ContainerAllocator>
struct myMessage_
{
  typedef myMessage_<ContainerAllocator> Type;

  myMessage_()
    : header()
    , strings()
    , number(0)  {
    }
  myMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , strings(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _strings_type;
  _strings_type strings;

   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::custom_messages_module::myMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages_module::myMessage_<ContainerAllocator> const> ConstPtr;

}; // struct myMessage_

typedef ::custom_messages_module::myMessage_<std::allocator<void> > myMessage;

typedef boost::shared_ptr< ::custom_messages_module::myMessage > myMessagePtr;
typedef boost::shared_ptr< ::custom_messages_module::myMessage const> myMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages_module::myMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages_module::myMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_messages_module

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'custom_messages_module': ['/home/thilina/development/robot_ws/Robot_ws/src/custom_messages_module/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages_module::myMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages_module::myMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages_module::myMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages_module::myMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages_module::myMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages_module::myMessage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages_module::myMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b00b856c143db6ef0fd80a0b141479ad";
  }

  static const char* value(const ::custom_messages_module::myMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb00b856c143db6efULL;
  static const uint64_t static_value2 = 0x0fd80a0b141479adULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages_module::myMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages_module/myMessage";
  }

  static const char* value(const ::custom_messages_module::myMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages_module::myMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string[] strings\n\
uint8 number\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::custom_messages_module::myMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages_module::myMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.strings);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages_module::myMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages_module::myMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "strings[]" << std::endl;
    for (size_t i = 0; i < v.strings.size(); ++i)
    {
      s << indent << "  strings[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strings[i]);
    }
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MODULE_MESSAGE_MYMESSAGE_H
